{
    'name':'Scolarite',
    'version':'1.0',
    'author':'Mohcine BAADI, Hamza SAKHRI',
    'category':'Management',
    'sequence':1,
    'description':"un module qui permet la gestion de scolarite",
    'images':[''],
    'depends': ['base', 'email_template'],
    'data': [
        'erp_student_view.xml', 
        'erp_announcement_view.xml', 
        'erp_request_view.xml',
        'erp_requesteddoc_view.xml',
        'erp_timetable_view.xml',
        'erp_registration_view.xml',
        'erp_classe_view.xml',
        'email_template.xml',
        ],
    'website':'scolarite@gmail.com',
    'update_xml':[],
    'js':[],
    'qweb':[],
    'css':['static/src/css/styles.css'],
    'demo':[],
    'test':[],
    'installable':True,
    'auto_install':False
}

