{
    'name':'Gestion Scolarite',
    'version':'1.0',
    'author':'Mohcine BAADI, Hamza SAKHRI',
    'category':'Gestion',
    'sequence':1,
    'description':"un module qui permet la gestion de scolarite",
    'images':[''],
    'depends':['base'],
    'data':['erp_etudiant_view.xml'],
    'website':'scolarite@gmail.com',
    'update_xml':[],
    'js':[],
    'qweb':[],
    'css':[],
    'demo':[],
    'test':[],
    'installable':True,
    'auto_install':False
}